### ISSUE TITLE
Issue with Insert() functionality

### ISSUE THREAD

**Issue by karite36** [cisc3130/1-vector#11]
I'm having an issue with Insert(), causing me to fail the assertion at line 57 of your main(). Please advise @rivlev

**Comment by rivlev** [comment]
Your code looks correct to me, and I can't replicate the failure
It runs fine without assertions failing

**Comment by karite36** [comment]
That's so weird that it's legitimately frustrating. I wonder why I'm having
the issue. Come think of it however, it might be something IDE related.
Don't you use VIM or something?

**Comment by karite36** [comment]
I never got a grade...
