### ISSUE TITLE
Error: no matching function for call to 'Vector<int>::Vector()'

### ISSUE THREAD

**Issue by noor-ul-karim** [cisc3130/1-vector#13]
Professor. @rivlev ,

I am having issue creating a vector v1 in the main.cpp file. 

`    int main()
     {
        srand (time(NULL));                
        const int ARRSIZE = rand() % 100;     
        int arr[ARRSIZE];

                           //arr[9], 9 elements
        for (int i = 0; i < ARRSIZE; i++) {     
          arr[i] = rand() % 100;                
        }

         Vector<int> v1;        // This line of code is giving me an error.               
        assert(v1.empty());                        
        for (int i = 0; i < ARRSIZE; i++)
        {         //9 repeats
          v1.push_back(arr[i]);                   
          assert(v1.size()==i+1);                  
          assert(v1[v1.size()-1]==arr[i]);     
          assert(v1[0]==arr[0]);                   
          assert(!v1.empty());                      
          assert(v1.at(i)==arr[i]);
        }`

**Comment by rivlev** [comment]
You implemented the vector constructor with two parameters (as in the fill constructor)
The main function expects a default constructor (with no parameters, creates empty vector)

**Comment by noor-ul-karim** [comment]
Professor @rivlev ,


Vector<int> v1;    //  Isn't this the default constructor ?

Vector<int> v1(5)    // and this is the fill constructor?

I am confused.
