### ISSUE TITLE
about the main.cpp

### ISSUE THREAD

**Issue by ghost** [cisc3130/1-vector#14]
Hi, Professor Levitan,
@rivlev 
I have some problem about the main.cpp. Do we need to modify main.cpp? I don't know if there is something wrong in main.cpp or my modified header file is wrong leading the error of the main.cpp. 
![20180222172834](https://user-images.githubusercontent.com/35934291/36568814-60dda1e8-17f9-11e8-8047-7251d6afe4a6.png)

**Comment by Huoliangchen** [comment]
My code for empty function:
bool empty() {
	 if(sz==0)
		 return true;
  }
