### ISSUE TITLE
Assertion failed: atleft, file main.cpp, line 82

### ISSUE THREAD

**Issue by FaustinoMalena** [cisc3130/1-vector#4]
Everything from check insertion to check erase passes. As main reaches check boundaries  line 82 fails is this a Vector header file problem or a main.cpp problem?
~Faustino Malena
@rivlev

**Comment by rivlev** [comment]
atleft checks that the method "at" will throw an exception if called with pos < 0. Have you implemented this?

**Comment by FaustinoMalena** [comment]
Yes I have now implemented it, I should do the same for all other functions that require this correct

**Comment by rivlev** [comment]
Yes
