### ISSUE TITLE
Assertion fails

### ISSUE THREAD

**Issue by NathVu** [cisc3130/1-vector#5]
In lines 30 and 31 of the cpp file it changes the value of v1.first to 3 and never changes arr or changes back v1.first. Because of this the code never makes it past the assert statement on line 61 because v1[0] != arr[0]. If i comment out that section, however, everything runs normally. Am I missing something?

**Comment by TestingYG** [comment]
Update your main.cpp. She posted a new one on Monday.

**Comment by NathVu** [comment]
thanks
