### ISSUE TITLE
Error connecting to Travis Cl

### ISSUE THREAD

**Issue by zeeshanmustafa** [cisc3130/1-vector#6]
I am having a issue connecting to Travis Cl . Every time I try to go in my Cisc3130 repository its giving me a message stating  " No Repositories found for organization cisc3130. The organization may not exist or you may not have sufficient permissions to view its repositories."

What should I do ?  @rivlev

**Comment by JunChen22** [comment]
Mine didn't show too in Travis ci .I just added my name to the Travis ci website and there's the activate button then it show up.And I also added my name to the README  so the status button show up as Pass/fail.
https://travis-ci.com/cisc3130/1-vector-YOURNAME

**Comment by rivlev** [comment]
It looks like you haven't told github classroom to create a 1-vector repository for you
Click through the Homework 1: Vectors link on the [class schedule](http://www.sci.brooklyn.cuny.edu/~levitan/data-structures/)
Once that repository is created, it should show up on travis
Please close if this works
