### ISSUE TITLE
Can't access travis ci

### ISSUE THREAD

**Issue by rivlev** [cisc3130/1-vector#8]
(reposted from private repository)

@rivlev I can't access travis ci at all, i thought it may have been due to me making a new branch, but change the master branch did nothing too solve the issue, I dont know what to do.

![travis](https://user-images.githubusercontent.com/31453557/30786932-40a23ade-a14c-11e7-9861-e933b4fcd031.PNG)

**Comment by rivlev** [comment]
@DullStudent

You need to click on cisc3130 on the left to find your repository. It doesn't belong to you (which is why it doesn't show up under your repositories), but you do have admin access.

You should always be able to find your repository by visiting the url (https://travis-ci.com/cisc3130/<NAME OF YOUR REPOSITORY>)

**Comment by DullStudent** [comment]
@rivlev is there a different link that link doesnt work.

![link doesnt work or not found](https://user-images.githubusercontent.com/31453557/30793144-e0384480-a18d-11e7-8ae5-6a725eb736f5.PNG)
