### ISSUE TITLE
Still Cant access Travis 

### ISSUE THREAD

**Issue by DullStudent** [cisc3130/1-vector#9]
@rivlev is there a different link? that link doesnt work. I couldn't come since I had class at 2:15pm. 

![link doesnt work or not found](https://user-images.githubusercontent.com/31453557/30793144-e0384480-a18d-11e7-8ae5-6a725eb736f5.PNG)

**Comment by drkitachi** [comment]
I am having the same issue.

**Comment by jseg787** [comment]
Same here

**Comment by drkitachi** [comment]
So I was able to add the repersitory and activate it by using the link https://travis-ci.com/cisc3130/1-vector-username (for username use your actual github username) thanks to @jseg787  however it shows me nothing to be build.

Here is the screeshot: https://ibb.co/b2ogDk

**Comment by JunChen22** [comment]
Try to add the link in the build/unknown ? The link you can find it in the redme.md but with your name added to the 1_vector.also need to open readme.md in text file not on the website

**Comment by jseg787** [comment]
Credit actually goes to @JunHaoChen [From here](https://github.com/cisc3130/1-vector/issues/6)

**Comment by DullStudent** [comment]
What about the branch? I can't switch to the hw branch I made

**Comment by DullStudent** [comment]
What about the branch? I can't switch to the hw branch I made

**Comment by JunChen22** [comment]
Change master to hw where master is in the link.the link has something like token .

**Comment by DullStudent** [comment]
Thanks for the Support!
